### ISSUE TITLE
Unable to build 1.7.2-1 (Fri 28 Aug 2020 08:34:24 AM) in Pacman (Manjaro)

### ISSUE THREAD

**Issue by billmccollam** [muriloventuroso/easyssh#104]
Unable to build

5/27] Compiling Vala source ../src/Application.vala ../src/Host.vala ../src/Account.vala ../src/Bookmark.vala ../src/MainWindow.vala ../src/Services/Settings.vala ../src/Views/SourceListView.vala ../src/Widgets/TerminalBox.vala ../src/Widgets/Welcome.vala ../src/Widgets/WelcomeAccounts.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/ConnectionEditor.vala ../src/Widgets/AccountEditor.vala ../src/Widgets/Connection.vala ../src/Widgets/ErrorRevealer.vala ../src/Widgets/Preferences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala ../src/Widgets/BookmarksPopover.vala ../src/Widgets/Tab.vala
FAILED: com.github.muriloventuroso.easyssh.p/src/Application.c com.github.muriloventuroso.easyssh.p/src/Host.c com.github.muriloventuroso.easyssh.p/src/Account.c com.github.muriloventuroso.easyssh.p/src/Bookmark.c com.github.muriloventuroso.easyssh.p/src/MainWindow.c com.github.muriloventuroso.easyssh.p/src/Services/Settings.c com.github.muriloventuroso.easyssh.p/src/Views/SourceListView.c com.github.muriloventuroso.easyssh.p/src/Widgets/TerminalBox.c com.github.muriloventuroso.easyssh.p/src/Widgets/Welcome.c com.github.muriloventuroso.easyssh.p/src/Widgets/WelcomeAccounts.c com.github.muriloventuroso.easyssh.p/src/Widgets/HeaderBar.c com.github.muriloventuroso.easyssh.p/src/Widgets/ConnectionEditor.c com.github.muriloventuroso.easyssh.p/src/Widgets/AccountEditor.c com.github.muriloventuroso.easyssh.p/src/Widgets/Connection.c com.github.muriloventuroso.easyssh.p/src/Widgets/ErrorRevealer.c com.github.muriloventuroso.easyssh.p/src/Widgets/Preferences.c com.github.muriloventuroso.easyssh.p/src/Widgets/TerminalWidget.c com.github.muriloventuroso.easyssh.p/src/Widgets/SearchToolbar.c com.github.muriloventuroso.easyssh.p/src/Widgets/BookmarksPopover.c com.github.muriloventuroso.easyssh.p/src/Widgets/Tab.c 
valac -C --debug --debug --define WITH_GPG --pkg vte-2.91 --pkg json-glib-1.0 --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gee-0.8 --color=always --directory com.github.muriloventuroso.easyssh.p --basedir ../ --gresources=../data/com.github.muriloventuroso.easyssh.gresource.xml ../src/Application.vala ../src/Host.vala ../src/Account.vala ../src/Bookmark.vala ../src/MainWindow.vala ../src/Services/Settings.vala ../src/Views/SourceListView.vala ../src/Widgets/TerminalBox.vala ../src/Widgets/Welcome.vala ../src/Widgets/WelcomeAccounts.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/ConnectionEditor.vala ../src/Widgets/AccountEditor.vala ../src/Widgets/Connection.vala ../src/Widgets/ErrorRevealer.vala ../src/Widgets/Preferences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala ../src/Widgets/BookmarksPopover.vala ../src/Widgets/Tab.vala
../src/Services/Settings.vala:54.17-54.37: warning: unhandled error `GLib.Error'
                file.make_directory();
                ^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:25.9-25.31: warning: `Gtk.UIManager' has been deprecated since 3.10
../src/MainWindow.vala:25.40-25.51: warning: `Gtk.UIManager' has been deprecated since 3.10
../src/MainWindow.vala:60.9-60.43: warning: `Gtk.ActionGroup' has been deprecated since 3.10
../src/Widgets/TerminalWidget.vala:174.17-174.31: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:181.25-181.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:174.17-175.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalWidget.vala:219.33-219.55: error: Argument 1: Cannot convert from `uint8[]' to `unowned char[]?'
                this.feed_child((uint8[])cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
../src/Widgets/TerminalBox.vala:107.33-107.55: error: Argument 1: Cannot convert from `uint8[]' to `unowned char[]?'
                term.feed_child((uint8[])cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:208.33-208.57: error: Argument 1: Cannot convert from `uint8[]' to `unowned char[]?'
                term.feed_child((uint8[])n_cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalBox.vala:199.33-199.55: error: Argument 1: Cannot convert from `uint8[]' to `unowned char[]?'
                term.feed_child((uint8[])cmd.to_utf8 ());
                                ^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1056.21-1056.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1058.49-1058.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1060.17-1060.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1067.25-1067.42: warning: unhandled error `GLib.Error'
                        file_ssh.delete ();
                        ^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1069.57-1069.109: warning: unhandled error `GLib.Error'
                    var dos_ssh = new DataOutputStream (file_ssh.create (FileCreateFlags.REPLACE_DESTINATION));
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1070.21-1070.56: warning: unhandled error `GLib.IOError'
                    dos_ssh.put_string (data_ssh_config);
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1109.21-1109.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1111.49-1111.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1113.17-1113.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1150.21-1150.34: warning: unhandled error `GLib.Error'
                    file.delete ();
                    ^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1152.49-1152.97: warning: unhandled error `GLib.Error'
                var dos = new DataOutputStream (file.create (FileCreateFlags.REPLACE_DESTINATION));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:1154.17-1154.37: warning: unhandled error `GLib.IOError'
                dos.put_string (data);
                ^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:140.13-140.27: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
../src/MainWindow.vala:35.9-35.42: warning: EasySSH.MainWindow.application hides inherited property `Gtk.Window.application'. Use the `new' keyword if hiding was intentional
        public Gtk.Application application { get; construct; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:475.13-475.82: warning: unhandled error `GLib.SpawnError'
            Process.spawn_command_line_async (default_filemanager + " " + command);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/MainWindow.vala:243.13-246.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:253.13-256.41: warning: unhandled error `GLib.SpawnError'
../src/MainWindow.vala:134.13-134.43: warning: `Gtk.Settings.gtk_menu_bar_accel' has been deprecated since 3.10
../src/MainWindow.vala:141.32-141.46: warning: `Gtk.ActionGroup' has been deprecated since 3.10
../src/MainWindow.vala:156.22-156.34: warning: `Gtk.UIManager' has been deprecated since 3.10
Compilation failed: 4 error(s), 28 warning(s)
[6/27] Compiling C object com.github.muriloventuroso.easyssh.p/meson-generated_.._as-resources.c.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by muriloventuroso** [comment]
Adicionei uma nova opção na versão 1.7.4 para lidar com as diferenças do VTE. Por favor use as opções patched-vte=false e ubuntu-bionic-patched-vte=true ao compilar.
