### ISSUE TITLE
Flatpak: used gnome runtime is end of life

### ISSUE THREAD

**Issue by rubikscraft** [muriloventuroso/easyssh#114]
Like the title says, the currently used runtime for the flatpak version is using `org.gnome.Platform//3.36`, but that version is end of life:
```
$ flatpak install easyssh
Looking for matches…
Found similar ref(s) for ‘easyssh’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Found ref ‘app/com.github.muriloventuroso.easyssh/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
Required runtime for com.github.muriloventuroso.easyssh/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.36) found in remote flathub
Do you want to install it? [Y/n]: y
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
```
So I suggest rebuilding the latest version for flatpak with a supported gnome platform.

**Comment by ryonakano** [comment]
It's already [fixed](https://github.com/flathub/com.github.muriloventuroso.easyssh/commit/d2802203ca9b9b70e3e1f76d21a6a7ebd60b432a) in the flathub repo side, but the build is failing and thus the fixed version is not seemd to be released yet.

I submitted two pull requests in the flathub repo and this repo to get everything works again (https://github.com/flathub/com.github.muriloventuroso.easyssh/pull/10 and #122).

**Comment by ryonakano** [comment]
@muriloventuroso You can close this issue since we merged https://github.com/flathub/com.github.muriloventuroso.easyssh/pull/10 :tada:

**Comment by KBeDevel** [comment]
This is an issue again since `org.gnome.Platform` (branch 41) is EOL.

Log output for reference:

```
Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.muriloventuroso.easyssh
```

**Comment by ryonakano** [comment]
@KBeDevel https://github.com/flathub/com.github.muriloventuroso.easyssh/pull/13 fixes that.
