### ISSUE TITLE
Please add new features 

### ISSUE THREAD

**Issue by Hammer2900** [muriloventuroso/easyssh#14]
Hi, great application ! Can you add some additional functionality like port froward, mount volume, export all connection to txt or zip archive with all information or key's ? Thank you !

**Comment by muriloventuroso** [comment]
Thanks for the feedback. These features seem very useful. You can wait for them in the next releases!

**Comment by Hammer2900** [comment]
Thank you for you response ) it will be great if we can store data on remote server and work with this data by REST protocol, say we can get all information by GET request and save it by POST, need implement two request for custom source. Some times you want get list of connection from home and work, yes you can export all connection but work with own server conveniently.

**Comment by muriloventuroso** [comment]
Forwarded ports: [add5236](https://github.com/muriloventuroso/easyssh/commit/add52363d93762ea6bb73be765334737e14dbf50)
Mount Volume: [a920761](https://github.com/muriloventuroso/easyssh/commit/a9207616fb0dd3987bb9aa91d4f2e6d3ed0c2a70)
