### ISSUE TITLE
Doubt translation

### ISSUE THREAD

**Issue by gallegonovato** [muriloventuroso/easyssh#164]
Good afternoon @muriloventuroso

First of all thank you for your time and help.

I happen to be using Weblate to help in the translation. And I have a question about a term. Which is https://hosted.weblate.org/translate/easyssh/glossary/en/?checksum=44bff6c5062d55e1&q=has%3Acomment . As you can see in the comments https://hosted.weblate.org/translate/easyssh/glossary/en/?checksum=44bff6c5062d55e1&q=has%3Acomment#comments we have a doubt. I think it refers to the abbreviation for Kentucky. Although if I remember correctly it would be KY in capital letters.

So I don't know if you would be so kind as to shed some light on this dilemma.

Thank you very much for your help and time

**Comment by muriloventuroso** [comment]
Hello,
Thanks for the help with the translation. I believe there was a failure in generating the translation file. The key "Ky" refers to the Kyrgyz language and should not be translated. I will fix this problem in Weblate.
