### ISSUE TITLE
Can't compile on Manjaro

### ISSUE THREAD

**Issue by FabioLolix** [muriloventuroso/easyssh#17]
Hi, maybe is due to recent Vala updates, seen similar errors with other programs

Vala: 0.40.7
GCC: 8.1.1
Meson: 0.46.1
Ninja: 1.8.2

There are three errors

```
../src/Widgets/TerminalWidget.vala:170.13-171.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalBox.vala:68.29-68.31: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
            term.feed_child(cmd, cmd.length + 1);
                            ^^^
../src/Widgets/TerminalBox.vala:140.29-140.38: error: Argument 1: Cannot convert from `string' to `unowned char[]?'
            term.feed_child(cmd + "\n", cmd.length + 1);
                            ^^^^^^^^^^
../src/Widgets/TerminalBox.vala:136.29-136.52: error: Argument 1: Cannot convert from `string' to `unowned char[]?'
            term.feed_child(dataHost.password + "\n", dataHost.password.length + 1);
                            ^^^^^^^^^^^^^^^^^^^^^^^^
../src/Views/SourceListView.vala:397.21-397.34: warning: unhandled error `GLib.Error'

```

and at the end

```
Compilation failed: 3 error(s), 13 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by muriloventuroso** [comment]
This error is caused by a change in the libvte API in versions greater than 0.52. I'll make a patch and as soon as available I'll flag here.

**Comment by FabioLolix** [comment]
Hello, I have the same problem again (for now compile with a Manjaro/Arch only [ugly patch](https://github.com/FabioLolix/PKGBUILD/blob/master/easyssh/0001-fix-vte-build-error.patch))

Had a similar problem with Polo file manager, hope Tony George solution might help

https://github.com/teejee2008/polo/commit/106cff10d707abbe21301084a918dd181893c161

https://github.com/teejee2008/polo/commit/942b3905e6ba08c54b9f528793345f40304ab75c

**Comment by muriloventuroso** [comment]
In the compilation the ubuntu-bionic-patched-vte option should be set to false.

**Comment by FabioLolix** [comment]
Great, thanks. Corrected the pkgbuild.
