### ISSUE TITLE
Login with public/private keys

### ISSUE THREAD

**Issue by muriloventuroso** [muriloventuroso/easyssh#23]
Allow authentication using public / private keys. It should be possible to create keys or use existing keys. 

I am open to suggestions.

**Comment by isneezy** [comment]
I've installed this wonderful tool, It works very well but get some annoying warnings about the key file

```sh
ssh user@myhost.com -p 22 -i file:///home/user/.ssh/key.pem
$ Warning: Identity file file:///home/user/.ssh/key.pem not accessible: No such file or directory.
```
I don't know if it is because the `file://` prefix

**Comment by muriloventuroso** [comment]
You were right, this file: // was messing up. Fixed in 69d4b22da69d80a557654d3d00055d99a6952e1d

**Comment by kkinder** [comment]
For me it seems to automatically use my ssh keychain.

**Comment by muriloventuroso** [comment]
The main idea was to integrate a key manager into EasySSH, to create and manage keys. For now, let's leave this for specialized applications such as seahorse.

**Comment by viczt** [comment]
Is it possible to specify password with key?
