### ISSUE TITLE
for windows 10 please

### ISSUE THREAD

**Issue by Oxicode** [muriloventuroso/easyssh#25]

**Comment by fitojb** [comment]
This is a Gtk+ program written in Vala with elementary OS’ Granite library. None of that is portable to Windows without requiring a complete rewrite. Have you tried [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by griffinwebnet** [comment]
you may be able to install the linux shell int o windows 10 and install it and run it from that shell
