### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by fethomm** [muriloventuroso/easyssh#31]
Sorry to use this for contact. I tried to make contact through LinkedIn, which did not work. I am writing an article on EasySSH and have a question or two. If you like, please contact me under linuxnews_at_mailbox.org. Thank you in advance.

**Comment by muriloventuroso** [comment]
Sorry for the delay. I got in touch by linkedin

**Comment by fethomm** [comment]
Thanks, just saw it. It's late here so I will message you per LinkedIn tomorrow.

greetings
Ferdinand
