### ISSUE TITLE
[Question] How to change UI language?

### ISSUE THREAD

**Issue by OzzieIsaacs** [muriloventuroso/easyssh#32]
I installed Easyssh on Linux Mint19 Tara via the mint application installer (which installs the flatpak version). In the source code on Github I saw that there are localizations available (e.g. for German).  But the UI is on my PC with "German Linux" in English, and I didn't find a switch or something else in the settings for changing the interface language. 
How is this supposed to work out?

**Comment by muriloventuroso** [comment]
The language of EasySSH is set automatically by the system default language. Please upgrade to the latest version and see if the translation is done correctly.

**Comment by OzzieIsaacs** [comment]
I tried new installation from commandline with flatpak. Result is still the same:
![bildschirmfoto vom 2018-10-25 21-22-32_](https://user-images.githubusercontent.com/6438895/47525358-573ed200-d89d-11e8-8c20-343c3358bccc.png)
I tried to remove the critcal error, but installing xdg-utils claims that it is already installed.
Command locale gives the following output:
LANG=de_DE.UTF-8
LANGUAGE=de_DE:de
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by muriloventuroso** [comment]
There was a major upgrade in the flatpak package, with the sdk and platform change. Could you update and check the translation?

**Comment by OzzieIsaacs** [comment]
I removed the flatpak installation, did a complete new installation installation of easyssh via: "flatpak install flathub com.github.muriloventuroso.easyssh", still the same:
![screenshot](https://user-images.githubusercontent.com/6438895/49684471-9c793500-fad4-11e8-9a94-d37010e18df6.png)
For your reference left side the .po file shows the translated string which should be displayed, so they are really translated. right side the easyssh screen. The error message regarding the missing xdg-mime is still the same, is this relevant?
I'm not so familiar with vala or flatpak, is there way to check if the newest version is installed?

**Comment by muriloventuroso** [comment]
flatpak run com.github.muriloventuroso.easyssh --version

The last version on flatpak is 1.4.5

**Comment by OzzieIsaacs** [comment]
![grafik](https://user-images.githubusercontent.com/6438895/49753594-34814500-fcb4-11e8-920a-a6596c9e6576.png)

**Comment by muriloventuroso** [comment]
I have verified the commit in your print of the info command and it is the last one.
The xdg-mime error is related to the default file manager. It has no influence on the translation problem. I will try to simulate this problem in another linux installation with flatpak.

**Comment by OzzieIsaacs** [comment]
Thanks

**Comment by ryonakano** [comment]
Fixed in #126, you can close this issue.
