### ISSUE TITLE
Can't Launch app

### ISSUE THREAD

**Issue by nickhq** [muriloventuroso/easyssh#34]
Am having trouble launching the app.

Am running **elementary OS 5.0 Juno** 

I have tried running the app from the terminal by executing `com.github.muriloventuroso.easyssh` 

I got the following output

```sh
nixon@Advanta:~$ com.github.muriloventuroso.easyssh 
**
ERROR:/build/com.github.muriloventuroso.easyssh-1.3.5/src/Views/SourceListView.vala:500:easy_ssh_source_list_view_load_ssh_config: assertion failed: (file != null)
Aborted
```

It used to work fine before untill I just stopped working some 3 days ago. I have tried uninstalling and re-installing the app from app center but am still not able to run it.

**Comment by muriloventuroso** [comment]
The file ~/.ssh/config not exists in your system.
