### ISSUE TITLE
Changes requested: release 1.4.3 lacking update information

### ISSUE THREAD

**Issue by cassidyjames** [muriloventuroso/easyssh#37]
Thanks for submitting an update to AppCenter! However, I've had to request changes on your latest release since there is no accompanying release information in your AppStream data. Please make a new release (i.e. 1.4.4) that also details the changes in your app since the last published release. Let me know if you have any questions.

**Comment by muriloventuroso** [comment]
Okay, I'll make the necessary changes. Thanks
