### ISSUE TITLE
Release version 1.4.5 to flatpak

### ISSUE THREAD

**Issue by saurabh73** [muriloventuroso/easyssh#39]
Kindly update the version in flatpak as the last version deployed is 1.4.0 as per [FLATPAK EasySSH](https://flathub.org/apps/details/com.github.muriloventuroso.easyssh)

**Comment by muriloventuroso** [comment]
flathub/com.github.muriloventuroso.easyssh@d417e0d142a07d7c94d59bf3f73da77fa043e6db

just wait the build
