### ISSUE TITLE
Feature Ideas: Shared User, Copy Functionality, Connection Indicator and Font Color

### ISSUE THREAD

**Issue by domsch1988** [muriloventuroso/easyssh#41]
Hi, great tool. I enjoy using on Solus quite a bit. Some things would make the live of people with many connections easier:
- Ability to copy connections
- Setting up a User/Password/Key-File combination to be used for several Servers
- Ability to set the Font/Foreground color per Connection
- Have some indication in the left list of open connections (Icon, or different font/background color for connected Sessions).

I appreciate the hardwork that went into making this tool!

**Comment by muriloventuroso** [comment]
It's great to know that. Let's try to add these features, but I need to understand them better.

- Ability  to copy connections
Could you explain this idea better?
- Setting up a User/Password/Key-File combination to be used for several Servers
Do you mean public and private key?
- Ability to set the Font/Foreground color per Connection
This functionality is now available in the Advanced section of the Connection Editor.
![image](https://user-images.githubusercontent.com/6272902/50174229-cb678600-02e0-11e9-9efc-81c126a74289.png)

- Have some indication in the left list of open connections (Icon, or different font/background color for connected Sessions).
This is a pretty cool idea, I'm going to study a way to implement it. If you have any ideas, you can tell me.

**Comment by domsch1988** [comment]
- Copy in a rather simple fashion: Have an option in the right click Menu to make a copy of an existing connection. I manage around 70 ish Linux Servers. Adding 8 Servers with the same login credentials, Group and IP apart from the last Number is a bit tedious atm. I'd like to just copy an existing connection and change the IP or Group.

- I ment like having the option to define a set of User/password or User/Private key that can be reused on several connections. This would allow changing the Password or Private key in a single place for several Servers at once. Maybe, to make management easier, it could be a Property of the group that gets inherited to the connections in that group. If you specify seperate credentials in a connection, those would overwrite the inherited credentials. Just one idea how this could work.
Maybe take a look at Terminus : https://www.termius.com/ they handle it in a kind of "Account Management" way. That's maybe overkill but gets across what i mean.

- Great to now. I'll look into that at work tomorrow.

- Well, i haven't done any GTK Applications so far, so no clue what their Interface guidelines say. I though about something like many Instant messengers to. A little green "dot" in front of currently active connections. Another idea would be the "Discord" way of making the title of connected sessions in the left colum green. But that's really minor. I just don't keep as many sessions open atm, so the Tabs work to keep an eye on where i'm currently connected to.

I highly appreciate the fast feedback and interest in my ideas. One reason i really enjoy your app is the great performance. Terminus has been really slow for me (Elektron plus Snap). So any change that would affect performance isn't a worthy tradeoff imho.

**Comment by muriloventuroso** [comment]
Account management: 1eff8a07855da36d979ff272b8e30daa8d1377d5
