### ISSUE TITLE
Long time connection can cause unresponsive input

### ISSUE THREAD

**Issue by Hentioe** [muriloventuroso/easyssh#42]
There is no such problem on `Termius`. Should `easyssh` use the heartbeat mechanism to keep the connection alive for a long time?

**easyssh version: 1.4.7**

**Comment by muriloventuroso** [comment]
EasySSH uses the default OpenSSH SSH installation on the system. In OpenSSH it is possible to configure a KeepAlive per connection in "~ / .ssh / config" or by default for all connections in "/ etc / ssh / sshd_config" by adding the following parameters:

ClientAliveInterval 300
ClientAliveCountMax 2

Use the values of your choice.
It would be interesting to have a more visual way of configuring these parameters in EasySSH. But I still can not say if it would be best for EasySSH to set these values by default or only if the user wishes.

**Comment by Hentioe** [comment]
Great, Thank you!

**Comment by Hentioe** [comment]
Let me take a moment to experiment

**Comment by Hentioe** [comment]
The problem has been solved, effective!
