### ISSUE TITLE
Error during instalation in Linux Mint

### ISSUE THREAD

**Issue by edmarmunhoz** [muriloventuroso/easyssh#46]
I am trying to install in Linux Mint and I am getting the error message:
![image](https://user-images.githubusercontent.com/8519109/52273440-05442880-2931-11e9-94e6-dc189b32b2d9.png)

**Comment by muriloventuroso** [comment]
Flathub service is down: http://flathub.com/

I hope it comes back fast.

**Comment by edmarmunhoz** [comment]
Yes, this is down, but this one is UP: https://flathub.org
Are not the same?

**Comment by muriloventuroso** [comment]
I am able to do the installation normally now. Can you do a test from the command line?

**Comment by edmarmunhoz** [comment]
Yes, it worked now.
Thanks a lot.
