### ISSUE TITLE
Bug in Preferences

### ISSUE THREAD

**Issue by griffinwebnet** [muriloventuroso/easyssh#47]
IN preferences, the font and terminal background color selections do not work. background color black is fine but the font is fuzzy and unreadable on terminal and changing the font and size in preferences nothing changes see below:

![scrot_easyssh](https://user-images.githubusercontent.com/1276255/53408048-3093c380-3983-11e9-978a-f6db3171bfbb.png)

**Comment by muriloventuroso** [comment]
Please make sure your connection configuration has terminal appearance settings. The Appearance settings of the Preferences menu apply to all new connections, but do not override custom settings for each connection.
![image](https://user-images.githubusercontent.com/6272902/53408478-4c0bc800-399d-11e9-9880-68b4f147fcdf.png)

**Comment by griffinwebnet** [comment]
First: thanks for the speedy reply!

so, okay cool that did indeed fix that im able to cheange settings per connection. however i just tried so many fonts i cant even count and all of them have this issue where the letter spacing is like  -5px so every letter overlaps making the connections completely unreadable which is actually why i was looking for this setting in the first place:

![screenshot from 2019-02-26 05-51-31](https://user-images.githubusercontent.com/1276255/53410856-98014180-398a-11e9-9b7d-d99a9485a068.png)

**Comment by muriloventuroso** [comment]
Have you tried a monospace font?

**Comment by griffinwebnet** [comment]
yep. i finally came across one that works called numbus mono. Its the only one that seems to. sans mono, roboto mono, ubuntu mono, and a handfull of other crazy font name monos all have the same overlapping issue. most other fonts wont even load they show up as square boxes and no characters. I realize mono fonts are generally chosen for terminal emulators, but coming from my general terminal emulator (Sakura) doing ssh connections via a command, i really just wanted a tabbed interface so i wouldnt have to do so much typing. Sakura terminal uses the standard Ubuntu font rather than the mono font without any hinting issues so im surprised to see such issues here.

**Comment by griffinwebnet** [comment]
summary here, my own confusion on that color thing. And the font issue i seem to have could very well be an issue unique to my system. i run an arch based system so perhaps im missing a package that exists in elementary that might ordinarily sort the hinting out.

Other than that the software is great. amazing work! sorry to take up your time on my issues lol

**Comment by muriloventuroso** [comment]
No problem, I'm glad you're enjoying it, that's what moves us to continue the work. I'm going to investigate these issues with fonts, are you using the Arch repository version?

**Comment by griffinwebnet** [comment]
yes. there are actually 2 versions in the AUR, easyssh and easyssh-git. im using easyssh

**Comment by maddin79** [comment]
Good Morning,

I have the same issue on Ubuntu 18.04. I build easyssh myself and the fonts are not readable., except the one griffinwebnet mentioned. Thanks for that. 

Best regards 
Martin
