### ISSUE TITLE
should use ssh agent 

### ISSUE THREAD

**Issue by vasyugan** [muriloventuroso/easyssh#48]
When I do normal ssh in a plain terminal, it is actually more convenient because ssh uses the ssh agent without me having to unlock the key each time. Why doesn't easyssh do the same?

**Comment by muriloventuroso** [comment]
How is your installation of EasySSH? Compiling the code or some packaging?

**Comment by vasyugan** [comment]
Am 11.03.19 um 14:24 schrieb Murilo Venturoso:
>
> How is your installation of EasySSH? Compiling the code or some packaging?
>
Flatpak

**Comment by muriloventuroso** [comment]
The installation with flatpak uses an own version of openssh and not the system version. In the next versions of the flatpak build I'm going to add the ssh-agent socket support.
