### ISSUE TITLE
Add bookmarks in easyssh

### ISSUE THREAD

**Issue by PrzemekSkw** [muriloventuroso/easyssh#49]
Hi, EasySSH is great app and will be much better with bookmarks for terminal commands. Is it possible to add such feature?

**Comment by muriloventuroso** [comment]
What's your idea for bookmarks?

**Comment by PrzemekSkw** [comment]
@muriloventuroso I think about bookmarks feature like in Tilix terminal emulator or goTerminal. So You can bookmark your fauvorite commands:
![Zrzut ekranu z 2019-03-27 12-31-30](https://user-images.githubusercontent.com/25219988/55072892-9b244600-508c-11e9-9dda-faf4c24bdd59.png)
