### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by MarcusMoeller** [muriloventuroso/easyssh#50]
Hi, I am trying to build EasySSH on Ubuntu 18.10 but got an error during ninja test: 

[1/20] Compiling Vala source ../src/Application.vala ../src/Host.vala ../src/Accou...erences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala.
FAILED: com.github.muriloventuroso.easyssh@exe/src/Application.c com.github.muriloventuroso.easyssh@exe/src/Host.c com.github.muriloventuroso.easyssh@exe/src/Account.c com.github.muriloventuroso.easyssh@exe/src/MainWindow.c com.github.muriloventuroso.easyssh@exe/src/Services/Settings.c com.github.muriloventuroso.easyssh@exe/src/Views/SourceListView.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalBox.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Welcome.c com.github.muriloventuroso.easyssh@exe/src/Widgets/WelcomeAccounts.c com.github.muriloventuroso.easyssh@exe/src/Widgets/HeaderBar.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ConnectionEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/AccountEditor.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Connection.c com.github.muriloventuroso.easyssh@exe/src/Widgets/ErrorRevealer.c com.github.muriloventuroso.easyssh@exe/src/Widgets/Preferences.c com.github.muriloventuroso.easyssh@exe/src/Widgets/TerminalWidget.c com.github.muriloventuroso.easyssh@exe/src/Widgets/SearchToolbar.c 
valac -C --debug --define UBUNTU_BIONIC_PATCHED_VTE --define=UNITY_SUPPORT=1 --define WITH_GPG --pkg unity --pkg gee-0.8 --pkg vte-2.91 --pkg json-glib-1.0 --pkg granite --pkg gtk+-3.0 --pkg glib-2.0 --pkg gee-0.8 --color=always --directory com.github.muriloventuroso.easyssh@exe --basedir ../ --gresources=../data/com.github.muriloventuroso.easyssh.gresource.xml ../src/Application.vala ../src/Host.vala ../src/Account.vala ../src/MainWindow.vala ../src/Services/Settings.vala ../src/Views/SourceListView.vala ../src/Widgets/TerminalBox.vala ../src/Widgets/Welcome.vala ../src/Widgets/WelcomeAccounts.vala ../src/Widgets/HeaderBar.vala ../src/Widgets/ConnectionEditor.vala ../src/Widgets/AccountEditor.vala ../src/Widgets/Connection.vala ../src/Widgets/ErrorRevealer.vala ../src/Widgets/Preferences.vala ../src/Widgets/TerminalWidget.vala ../src/Widgets/SearchToolbar.vala
unity.vapi:97.4-97.13: warning: [Deprecated] is deprecated. Use [Version (deprecated = true, deprecated_since = "", replacement = "")]
../src/Services/Settings.vala:52.17-52.37: warning: unhandled error `GLib.Error'
                file.make_directory();
                ^^^^^^^^^^^^^^^^^^^^^
../src/Widgets/TerminalWidget.vala:120.21-120.30: warning: Gtk.Menu.popup has been deprecated since 3.22
../src/Widgets/TerminalWidget.vala:172.13-172.27: warning: Vte.Terminal.spawn_sync has been deprecated since 0.48
../src/Widgets/TerminalWidget.vala:172.13-173.101: warning: unhandled error `GLib.Error'
../src/Widgets/TerminalWidget.vala:201.33-201.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
                this.feed_child(cmd, cmd.length);
                                ^^^
../src/Widgets/SearchToolbar.vala:97.21-97.42: warning: Vte.Terminal.search_set_gregex has been deprecated since 0.46
../src/Widgets/TerminalBox.vala:89.33-89.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
                term.feed_child(cmd, cmd.length);
                                ^^^
../src/Widgets/TerminalBox.vala:190.33-190.37: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
                term.feed_child(n_cmd, cmd.length);
                                ^^^^^
../src/Widgets/TerminalBox.vala:181.33-181.35: error: Argument 1: Cannot convert from `unowned string' to `unowned char[]?'
                term.feed_child(cmd, cmd.length);
                                ^^^

ninja install also fails.

**Comment by muriloventuroso** [comment]
This is a breach of compatibility with libvte. There is a path to get around it, you must compile with the ubuntu-bionic-patched-vte = false option.

https://github.com/muriloventuroso/easyssh/issues/24

**Comment by MarcusMoeller** [comment]
This is already set in meson_options.txt - build/build.ninja: COMMAND = /usr/bin/python3 /usr/bin/meson --internal scanbuild /.../easyssh /.../easyssh/build /usr/bin/python3 /usr/bin/meson -Dlibunity=true -Dubuntu-bionic-patched-vte=true -Dwith-gpg=true

It's cosmic, 18.10 where I am trying to build. Not sure if that matters.

**Comment by muriloventuroso** [comment]
You need to set false
