### ISSUE TITLE
Can't quit htop

### ISSUE THREAD

**Issue by lamka02sk** [muriloventuroso/easyssh#56]
F10 to exit htop does not work at all. I have to close/reopen tab to continue.

**Comment by muriloventuroso** [comment]
I'll investigate the problem. In the meantime you can use the Q key to exit the htop without having to close the tab.

**Comment by lamka02sk** [comment]
Thank you very much, didn't know about Q

**Comment by brackenhill-mob** [comment]
+1

I'm a heavy Midnight Commander user and F10 is really important otherwise I can't exit ;)

**Comment by ITarrant** [comment]
+1
I also use Midnight Commander often and F10 is required
