### ISSUE TITLE
First character from line selection issue

### ISSUE THREAD

**Issue by stderr-to-devnull** [muriloventuroso/easyssh#66]
Kubuntu 19.04, EasySSH 1.6.2 Flatpak:

Can't fully select for copy a specific line, first character cannot be selected because mouse will go to panel border/resizing instead.

**Comment by stderr-to-devnull** [comment]
App is still version 1.6.2 on https://flathub.org/apps/details/com.github.muriloventuroso.easyssh

**Comment by muriloventuroso** [comment]
In flatpak the releases take a little longer.
