### ISSUE TITLE
Feature request: possibility to open a localhost terminal

### ISSUE THREAD

**Issue by shaphiro** [muriloventuroso/easyssh#68]
Hi, as in other ssh connection managers, it would be nice to have the possibility to open localhost terminals. What do you think about?

**Comment by muriloventuroso** [comment]
I am in doubt about what is the use of this feature. Would it be another terminal option?

**Comment by shaphiro** [comment]
Yes, like in Gnome Connection Manager for example, it would be convenient to be able to open both ssh remote connections and local terminal sessions within Easyssh.

![gcm](https://user-images.githubusercontent.com/9846064/65068361-d000be00-d988-11e9-846a-b9060e5d2a57.png)
