### ISSUE TITLE
Unable to open an ssh connection within another ssh connection

### ISSUE THREAD

**Issue by shaphiro** [muriloventuroso/easyssh#69]
It seems impossibile to open an ssh connection inside the easyssh terminal. Step to reproduce the bug:

1) open an ssh connection to the server with easyssh
2) open an ssh connection with the ssh cli command
3) see the attached screenshot. 

About the wrong password error "Permission denied, please try again": I didn't type anything (no password supplied). It is easyssh that has entered something...

Client OS: Ubuntu 18.10
The 192.168.2.2 machine is an openwrt

Thanks

![easybug](https://user-images.githubusercontent.com/9846064/65493106-77fb1780-deb2-11e9-90b3-0a3c5b3ef6b8.png)

**Comment by viczt** [comment]
Its reproduced when client and both servers are in same subnet.
Also annoying that tab closes after error. (
