### ISSUE TITLE
Inconsistent copy-paste behavior

### ISSUE THREAD

**Issue by stderr-to-devnull** [muriloventuroso/easyssh#80]
When attempting to copy through classic selection of terminal text of multiple lines, the selected lines are not copied.
Also copying this way a single line, is only available  to paste via middle click button. This is not consistent with how copy works in virtually any other apps or Linux terminal and creates a lot of confusion.

**Comment by muriloventuroso** [comment]
Can you better explain how you are trying to copy and paste? I tested using the shortcut Ctrl + Shift + C and Ctrl + Shift + V on multiple lines and also a single line and all worked well.

**Comment by stderr-to-devnull** [comment]
I am doing the copy-pasting with the mouse (right click and/or middle click)

**Comment by muriloventuroso** [comment]
I was unable to reproduce inconsistencies in the copy / paste behavior. I will close the issue, if the problem persists feel free to reopen it with more information.
