### ISSUE TITLE
Critical error ! Changes not saved !

### ISSUE THREAD

**Issue by kakogoxepa** [muriloventuroso/easyssh#85]
EasySSH - 1.6.4 work on Elementary OS 5.0 Juno 
(Built on Ubuntu 18.04.2 LTS; Linux 4.15.0-66-generic; GTK 3.22.30)

I use the program for about six months. Everything used to be fine.
But there was an error in this version (1.6.4).

I can add and remove new hosts without problems.
But the old hosts added in previous changes I can not change or delete.

For example, I go into the program, delete the old hosts, wait 1-2 minutes, close the program, then open it again and see. That the hosts that I deleted still exist.

I tried 10-20 times. The problem exists. Installed all system updates, rebooted the computer 3 times. Nothing helps.

**Comment by muriloventuroso** [comment]
Can you verify that the EasySSH configuration file has write permission?

**Comment by kakogoxepa** [comment]
@muriloventuroso Hello ! Please tell me whether it is planned to fix this bug?

**Comment by muriloventuroso** [comment]
@kakogoxepa  When you delete the host is it still displayed in the sidebar or is it removed and only reappeared when the program is reopened? Are you using encryption? Are you using synchronization with SSH Config?

**Comment by kakogoxepa** [comment]
@muriloventuroso removed and only reappeared when the program is reopened.

**Comment by kakogoxepa** [comment]
![temp](https://user-images.githubusercontent.com/39045905/68584008-8b2c6b80-048f-11ea-826a-686be51cbd84.png)

**Comment by kakogoxepa** [comment]
@muriloventuroso Tell me please

what should I do ? wait for a new version with bug fix?

Or

Delete the current configuration files and re-fill everything?

**Comment by muriloventuroso** [comment]
@kakogoxepa  I still can't reproduce the error locally. Even using the flatpak version I can do all the operations normally. I believe the problem is occurring while saving the new configuration file. Could you do a test without data encryption?

**Comment by kakogoxepa** [comment]
@muriloventuroso I disabled encryption. I closed the program. I opened the program, deleted these 5 entries, closed the program. Opened it again, but the notes remained. Don't was removed.
![image](https://user-images.githubusercontent.com/39045905/68585618-ce88d900-0493-11ea-9bca-1e701c716adc.png)

**Comment by kakogoxepa** [comment]
When i deleted

`amedov@BOSS:~$ com.github.muriloventuroso.easyssh
0
(com.github.muriloventuroso.easyssh:9287): Gtk-WARNING **: 14:54:14.924: Attempting to add a widget with type GraniteWidgetsDynamicNotebook to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
1
(com.github.muriloventuroso.easyssh:9287): Gtk-WARNING **: 14:54:17.359: Attempting to add a widget with type GraniteWidgetsDynamicNotebook to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
2
(com.github.muriloventuroso.easyssh:9287): Gtk-WARNING **: 14:54:18.804: Attempting to add a widget with type GraniteWidgetsDynamicNotebook to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
3
(com.github.muriloventuroso.easyssh:9287): Gtk-WARNING **: 14:54:19.985: Attempting to add a widget with type GraniteWidgetsDynamicNotebook to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.
4
(com.github.muriloventuroso.easyssh:9287): Gtk-WARNING **: 14:54:21.122: Attempting to add a widget with type GraniteWidgetsDynamicNotebook to a container of type GtkBox, but the widget is already inside a container of type GtkBox, please remove the widget from its existing container first.`

**Comment by kakogoxepa** [comment]
@muriloventuroso I have a computer at work. Home laptop and computer. Everywhere is the same version of Elementari OS. This problem is everywhere.

And she appeared after updating to 1.6.4
