### ISSUE TITLE
Modifying an existing connection crashes easyssh

### ISSUE THREAD

**Issue by stderr-to-devnull** [muriloventuroso/easyssh#86]
Kubuntu 19.04, easyssh 1.6.3

I had several SSH connections open, I edited one (same server but different user), after save, easyssh crashed (closed without error)

**Comment by muriloventuroso** [comment]
Can you run EasySSH from the terminal and check for any error output?

**Comment by kakogoxepa** [comment]
@muriloventuroso segmentation fault

![image](https://user-images.githubusercontent.com/39045905/67931278-8edc0a80-fbd2-11e9-890c-47010f0524ad.png)

**Comment by muriloventuroso** [comment]
@kakogoxepa can you update to version 1.6.4 and retest?

**Comment by kakogoxepa** [comment]
@muriloventuroso specifically this problem, 100% manifests itself in 1.6.3 and 1.6.4.
Checked on one computer and on one laptop. Both there and there used Elementary OS

**Comment by stderr-to-devnull** [comment]
`flatpak run com.github.muriloventuroso.easyssh

** (com.github.muriloventuroso.easyssh:2): CRITICAL **: 04:48:50.128: file /run/build/easyssh/src/MainWindow.vala: line 237: uncaught error: Failed to execute child process “xdg-mime” (No such file or directory) (g-exec-error-quark, 8)

(com.github.muriloventuroso.easyssh:2): Gtk-CRITICAL **: 04:48:59.956: gtk_grid_attach: assertion '_gtk_widget_get_parent (child) == NULL' failed

(com.github.muriloventuroso.easyssh:2): Gtk-WARNING **: 04:48:59.958: gtkwidget.c:8629: widget not within a GtkWindow

** (com.github.muriloventuroso.easyssh:2): CRITICAL **: 04:49:09.017: easy_ssh_connection_construct: assertion 'host != NULL' failed

(com.github.muriloventuroso.easyssh:2): GLib-GObject-CRITICAL **: 04:49:09.017: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

** (com.github.muriloventuroso.easyssh:2): CRITICAL **: 04:49:09.017: easy_ssh_host_get_name: assertion 'self != NULL' failed

** (com.github.muriloventuroso.easyssh:2): CRITICAL **: 04:49:12.199: granite_widgets_tab_get_page: assertion 'self != NULL' failed`

**Comment by muriloventuroso** [comment]
Can you check if the issue has been resolved in release 1.6.5?

**Comment by kakogoxepa** [comment]
@muriloventuroso In the Elementary OS store, version 1.6.5 is not yet available. I tried to put a flatpack version. There this bug is fixed. But in the flatpack version there are other bug (Error accessing file /home/username/.ssh/id_rsa).

I will wait when a new version appears in the market Elementary OS

**Comment by stderr-to-devnull** [comment]
Unfortunately it is still happening on 1.6.5 for me

**Comment by muriloventuroso** [comment]
Fixed in lasted version
