### ISSUE TITLE
Exiting from a SSH session  established inside an easyssh session will also close (ungraceful) the easyssh session

### ISSUE THREAD

**Issue by stderr-to-devnull** [muriloventuroso/easyssh#87]
Kubuntu, easyssh 1.6.3

Exiting from a SSH session established inside an easyssh session will also close (ungraceful) the easyssh session. This closed easyssh session will also remain present on the system until it will time out our manually closed.

**Comment by muriloventuroso** [comment]
Fixed in e59771d49cf4b4c773f0e09920c5e7366574c009
