### ISSUE TITLE
Server waits for a password

### ISSUE THREAD

**Issue by Hukuta** [muriloventuroso/easyssh#89]
It started a couple of days ago. I click "Connect", a password prompt appears and the program does not enter it (password). It is useless to wait. Then I press Enter, the server fails because the password is incorrect, gives a second try, then the easyssh enters the correct password and the server allows. The problem repeats with different servers.

**Comment by muriloventuroso** [comment]
Can you pass me the content displayed by SSH when requesting the password?

**Comment by Hukuta** [comment]
![Selection_072](https://user-images.githubusercontent.com/3100053/68971040-5141c900-07f1-11ea-80de-1edb79fb8820.png)

**Comment by muriloventuroso** [comment]
Please check the last release.
